/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jh.craft.interpreter;

import jh.craft.interpreter.scanner.Scanner;

import java.nio.file.Files;
import java.nio.file.Path;

public class Main {
    public static void main(String[] args) {
        if( args.length < 1 ){
            System.err.println("usage: main <filename>");
            System.exit(1);
        }

        var filename = args[0];
        try{
            var source = Files.readString( Path.of( filename ) );
            for (var token : Scanner.scanTokens( source ).value()){
                System.out.println("- " + token);
            }
        }catch (Exception ex){
            System.err.printf("Error reading '%s': %s\n", filename, ex);
            System.exit(1);
        }

    }
}
