#! /usr/bin/env sh

set -e
# BY NOW!!
case "$1" in
    -b|--build)
        echo "-> building jlox"
        ./gradlew build
        ./scripts/ast_generator.py
        shift
    ;;
esac

echo "-> running jlox"
java -jar build/libs/*.jar $*


